language: python

install:
  - pip install tox

script: tox -e $TOXENV

matrix:
  include:
    - python: 3.5
      env: {TOXENV: py35}
    - python: 3.5
      env: {TOXENV: coverage, COVERAGE: 1}
      before_install:
        - "pip install codecov"
      after_success:
        - "codecov"
    - python: 3.5
      env: {TOXENV: lint}
    - language: node_js
      node_js: "node"
      install: "cd fava/static; npm install"
      script: "cd fava/static; npm run lint"

cache:
  directories:
    - $HOME/.cache/pip
    - fava/static/node_modules
