build: false
version: '{build}'
platform: x64
environment:
  PYTHON: 'C:\Python37'
  PYTHONIOENCODING: ':replace'

install:
  - '%PYTHON%\python -m pip install -U setuptools pip wheel tox'

test_script:
  - '%PYTHON%\python setup.py build_ext --inplace'
  - '%PYTHON%\scripts\tox -e py'

cache:
  - '%LOCALAPPDATA%\pip\cache'
  - '.tox -> setup.cfg'
