name: Test

on:
    workflow_dispatch:
        # workflow_dispatch allows the workflow to be triggered manually, see:
        # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                python-version: [3.6, 3.9]
                os: [windows-latest, macos-latest, ubuntu-latest]

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Set up Node
              uses: actions/setup-node@v1
              with:
                  node-version: "14"
            - name: Install tox
              run: pip install tox
            - name: Install node dependencies
              run: cd frontend && npm ci
            - name: pre-commit
              if: ${{ matrix.os == 'ubuntu-latest' }}
              uses: pre-commit/action@v2.0.0
            - name: Lint
              if: ${{ matrix.os == 'ubuntu-latest' }}
              run: tox -e lint
            - name: Test
              run: make test
            - name: Install pyinstaller
              run: pip install pyinstaller
            - name: Install fava
              run: pip install .
            - name: Build and test the pyinstaller binary
              run: make pyinstaller-test
